[package]
name = "hashoverlay-settings"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/gut0to/LMU-Overlay"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
overlay-renderer = { path = "../../crates/overlay-renderer" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
toml = "0.8"
