[package]
name = "overlay-renderer"
version = "1.0.2"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
serde.workspace = true
telemetry-engine = { path = "../telemetry-engine" }
lmu-telemetry = { path = "../lmu-telemetry" }
toml.workspace = true
windows-sys.workspace = true
windows.workspace = true
windows-numerics.workspace = true
